services:
  consul:
    container_name: consul
    image: hashicorp/consul:1.17
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  product-postgres:
    container_name: products-postgres
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - ./product/src/main/resources/.env
    healthcheck:
      start_period: 1s
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]

  haproxy:
    container_name: haproxy
    image: haproxy:2.9-alpine
    ports:
      - "8081:8081"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"