server:
  error:
    include-message: always
  port: 8085
  ssl:
    key-store: classpath:localhost.p12
    key-store-password: storepassword
    key-alias: localhost
    enabled: false
spring:
  config:
    import: .env[.properties]
  application:
    name: "product-service"
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${server.port}:${random.value}
        service-name: ${spring.application.name}
        prefer-ip-address: true
        hostname: localhost
        health-check-interval: 10s
        health-check-path: /actuator/health
        health-check-critical-timeout: 30s
        register: true
        deregister: true
        tags:
          - "version=1.0"
          - "team=soa-lab2"
          - "environment=development"
        metadata:
          description: "Product management service"
          swagger-url: "http://localhost:${server.port}/swagger-ui.html"
springdoc:
  api-docs:
    path: '/v3/api-docs'
    enabled: true
  swagger-ui:
    path: '/swagger-ui.html'
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always