server:
  port: 8080
  ssl:
    key-store: classpath:localhost.p12
    key-store-password: storepassword
    key-alias: localhost
    enabled: false
  error:
    include-message: always
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${server.port}:${random.value}
        service-name: ${spring.application.name}
        prefer-ip-address: true
        hostname: localhost
        health-check-interval: 10s
        health-check-path: /actuator/health
        health-check-critical-timeout: 30s
        register: true
        deregister: true
        tags:
          - "version=1.0"
          - "team=soa-lab2"
          - "environment=development"
        metadata:
          description: "API Gateway with service discovery"
    gateway:
      httpclient:
        ssl:
          trusted-x509-certificates: classpath:root_ca.crt
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: products-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: ebay-service
          uri: https://localhost:8082
          predicates:
            - Path=/api/ebay/**