server:
  port: 8080
  ssl:
    key-store: classpath:localhost.p12
    key-store-password: storepassword
    key-alias: localhost
    enabled: false
  error:
    include-message: always
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      httpclient:
        ssl:
          trusted-x509-certificates: classpath:root_ca.crt
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: products-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: ebay-service
          uri: https://localhost:8082
          predicates:
            - Path=/api/ebay/**